# mkdocs.yml
site_name: E-commerce Data Pipeline - Projeto Final Engenharia de Dados
site_description: Documentação do projeto de engenharia de dados - UNISATC
site_author: Deyvid Charles Souza de Negreiros, Diogo Dias de Abreu Alves,Lucas Perito Lucas, Marcos Vinicius Goudinho da Silva, Nicolas Andrade de Freitas e Vitor Valcanaia Rosendo Martins
site_url: https://nicolasfreitas1.github.io/trabalho-final-engenharia-dados/

# Repository
repo_name: NicolasFreitas1/trabalho-final-engenharia-dados
repo_url: https://github.com/NicolasFreitas1/trabalho-final-engenharia-dados.git

# Configuration
theme:
  name: material
  language: pt
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Modo claro
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Modo escuro
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

# Navigation
nav:
  - Home: index.md
  - Configuração do Ambiente: sobre.md
  - Documentação:
    - Upload de Banco de Dados: updload-database.md
    - Automação com Airflow: airflow-automation.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - attr_list
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      lang: pt